version: "3.8"

services:
  bot:
    build: .
    container_name: tori_notify_bot
    volumes:
      - sqlite_data:/app/database.db
    environment:
      - BOT_TOKEN=7665233820:AAHcu1sa_0LVxN45_7ldxMD_iVqs6_3NWp0
      - ALLOWED_CHAT_ID=-1002405799261
      - DATABASE_URL=sqlite:///app/database.db
    restart: always

volumes:
  bot_data:  # Define a persistent volume
